### PR TITLE
Update production configs

### LINKED ISSUE #139: RUNNING_PID problems
After sudden rebooting the host machine service was not started either automatically or manually. I've got the following from its logs:

```
This application is already running (Or delete /opt/loglist/RUNNING_PID file).
```

So, I've deleted the `/opt/loglist/RUNNING_PID` file and was able to start it again.

We need to automatically delete this file or create it on `/tmp`.

See also #140: the service is unable to autostart because of this.

### PR DESCRIPTION
**Pull request by ForNeVeR**
I've added an automatic restart for systemd and disabled the pidfile. That'll help us to restart the service in cause of any troubles such as #196 in future.

Closes #139.

### CODE REVIEW

**Comment by Minoru** [comment]
In #139 you mentioned we should create PID files in temporary storage like `/tmp`. Why did you decide against this? (`/run` is commonly used to store PID files AFAIK.)

Other than that, it looks good to me.

**Comment by ForNeVeR** [comment]
@Minoru I can't see any purpose for that file in our current setup. Also, storing that in `/tmp` wouldn't solve the problem: `/tmp` is cleaned only on server restart, but our current issue is that OOM Killer sometimes kills the service (without stopping the whole machine, obviously).

**Comment by Minoru** [comment]
Ah; #139 mentions a sudden reboot, so I got confused.

Anyway, I don't see any other pragmatic solution, so I declare this good to merge.

**Comment by ForNeVeR** [comment]
Thanks for the review, guys!

**Pull request merged**
