### PR TITLE
Error catching into shell scripts

### PR DESCRIPTION
**Pull request by Cuttlerat**
It's dangerous to not check if directory is exists.

### CODE REVIEW

**Comment by ForNeVeR** [comment]
Mr. @Minoru, could you review that, please? I'm not an expert in these matters, but I think we had similar discussion with you some time ago.

**Comment by ForNeVeR** [comment]
Yup, I pretty much believe that we have settled usage of `set -e` for the same purpose in [our other website project](https://github.com/codingteam/codingteam.org.ru/blob/1a7c5c50be0ce6a8849fa8d8ceb50cbaf1df6ed6/scripts/stop.sh).

Will that `set -e` also fix the problem with non-existent directories? I'd then vote for using `set -e` for consistency everywhere.

**Comment by Cuttlerat** [comment]
Yes, `set -e` would work much better and I think it's more valuable here

**Comment by ForNeVeR** [comment]
Could you please update your PR with `set -e` instead of `exit 1`?

**Comment by ForNeVeR** [comment]
Well, I'll merge that. Mr. @Minoru, feel free to comment the issue after the merge!

@Cuttlerat, thanks a lot for the contribution.

**Pull request merged**
