### PR TITLE
Use Session.getInstance of JavaMail

### LINKED ISSUE #143: Don't use Session.getDefaultInstance from JavaMail
Usage of this method can become a potential bug in the future: [Notifications.scala](https://github.com/codingteam/loglist/blob/59c7e5ec427337b2da8ca08c165e32f41de5f6bf/scalajvm/app/helpers/Notifications.scala#L57). See [JavaMail FAQ](http://www.oracle.com/technetwork/java/faq-135477.html#getdefaultinstance) for more information.

We should use `Session.getInstance` instead.

### PR DESCRIPTION
**Pull request by rexim**
Close #143

### CODE REVIEW

**Comment by rexim** [comment]
@ForNeVeR any updates on this one?

**Comment by rexim** [comment]
Please don't say you didn't receive any notifications ._.

**Comment by ForNeVeR** [comment]
This PR looks good to me.
Although I will merge this only after I get back to home. We have autodeployment system set up on this project, and I'll need to monitor it in lab conditions to check whether it is alive and have no malfunctions.

**Comment by rexim** [comment]
@ForNeVeR alright! Thanks for the explanation! Looking forward to it.

**Comment by rexim** [comment]
Any updates Mr @ForNeVeR?

**Comment by ForNeVeR** [comment]
Sorry, still no.

**Comment by ForNeVeR** [comment]
Well, let the fun begin.

**Comment by ForNeVeR** [comment]
Okay, I can confirm that our archeotech is working.

**Comment by rexim** [comment]
Thank you Mr @ForNeVeR! You are da best!!

**Pull request merged**
