### PR TITLE
[WIP] Update Scala.js

### LINKED ISSUE #186: Update Scala.js
This is surprisingly complex task until we've done migration from Play framework. I have done some initial work in [feature/frontend](https://github.com/codingteam/loglist/tree/feature/frontend), but currently I cannot build it with `fullOptJS` because of some Play+RhinoJS inconsistencies. Maybe we'll revisit this branch later.

### PR DESCRIPTION
**Pull request by ForNeVeR**
Should fix #186. Currently it cannot be built, we're investigating the issue.

### CODE REVIEW

**Comment by hagane** [comment]
It's a prime example of jar hell (as opposed to horta hell which is a good thing). Apparently some gorram hipster decided it's pretty smart to use both ` "io.apigee" % "rhino" % "1.7R5pre4"` and ` "org.mozilla" % "rhino" % "1.7R4"`. I'll try to deduce the latest version of scalajs plugin lacking this idiocy.

**Comment by hagane** [comment]
Oh, nevermind, `org.mozilla:rhino:1.7R4` is pulled by `io.apigee.trireme:trireme-core:0.7.5`

**Comment by hagane** [comment]
And THAT shit is pulled by SBT plugins like `"com.typesafe.sbt" % "sbt-less" % "1.0.0"` and `"com.typesafe.sbt" % "sbt-mocha" % "1.0.0"`. Oy vey. Their versions probably should be bumped too.

**Comment by rexim** [comment]
@ForNeVeR is this still relevant?

**Comment by ForNeVeR** [comment]
Yes it is. We still haven' updated the damn' scala.js.

**Comment by rexim** [comment]
@ForNeVeR I think this PR is dead. Let's close it?

**Comment by ForNeVeR** [comment]
I don't think it's dead. We want to eventually update our Scala.js. Somebody should take it and finish the work. The changes in this PR are useful.

**Comment by rexim** [comment]
@ForNeVeR if I was assigned to fix #186 right now I'd just start from scratch. Just sayin'. You do you. :)

**Comment by ForNeVeR** [comment]
@rexim you're right: sometimes I have difficulties differentiating myself from other people. So, if I will be you when I'll be fixing the issue, I'll probably start from scratch. Otherwise I'll likely take another ~~pills~~ actions.

**Comment by Minoru** [comment]
Superseded by #225 which updates Scala.js to 1.2.0 (amongst other things).

**Pull request closed without merging**
